development:
  adapter: postgresql
  encoding: unicode
  database: dj_test_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: dj_test_test
  pool: 5
  username: postgres
  password: postgres
